### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by some-sh** [JoshPaulie/EveryMovieEver#1]
- I'd use the `pathlib` standard library to handle file paths. As you mentioned in your [tweet](https://twitter.com/itsBexli/status/1505920152986001412) that your friend uses Windows, the current implementation might break, not sure though. But better to be safe, right? 
- I couldn't understand the need to proceed further in the loop at this [point](https://github.com/JoshPaulie/EveryMovieEver/blob/main/eme/EveryMovieEver.py#L46) , because if the fuzzy match output is what the user wanted to add to the list, there's no point in looping over the matches further. Am I wrong here?
- Instead of coupling the movie description along with the name, the movie description can be added as a separate column in the table. A seperate value in the file. In that case it'd be better it is a csv file
- Few more fields can be added like his ratings, date he watched (which can be automatically added when a new entry is added) and description as mentioned in the previous point, etc.

**Comment by JoshPaulie** [comment]
> I'd use the pathlib standard library to handle file paths.

I'll look into the pros and cons. If it's a safer option, I'm very interested

> I couldn't understand the need to proceed further in the loop at this point

You're right, and the part I wanted feedback on. It's unlikely he would fuzzy match the title of multiple movies.

> Instead of coupling the movie description along with the name
> Few more fields can be added

The only descriptions of movies are placeholders for movies he forgot the title of. I pitched the idea of a csv file to include more, but he only wants to track the title


Thank you again for your time! @some-sh
